apiVersion: v1
name: juniper-jti
version: 0.1.1
appVersion: 0.1.0
description: Synse plugin to consume Juniper networking telemetry (JTI) over UDP
home: https://github.com/vapor-ware/synse-juniper-jti-plugin
icon: https://charts.vapor.io/.images/synse-server-chart.jpg
sources:
  - https://github.com/vapor-ware/synse-juniper-jti-plugin.git
maintainers:
  - name: Erick Daniszewski
    email: erick@vapor.io
