# Default values for juniper-jti-plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Partially override the fullname template (will maintain the release name).
nameOverride: ""

## Fully override the fullname template.
fullnameOverride: ""

## Image configuration options.
image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/juniper-jti-plugin
  tag: "0.1.0"
  pullPolicy: Always

## Enable/disable application metrics export via Prometheus.
metrics:
  enabled: false

## Define the port which the plugin's UDP server is configured to listen on
## (via the `config` block). This is required in order to expose the port for
## incoming streamed JTI data.
##
## FIXME (etd): This is not an ideal way of defining this config, as it is
##   a duplicate config option from what is listed in the `config` block,
##   but there doesn't seem to be a clean, easy way of deduplicating the
##   config, so for the initial version of the chart, this is okay. If this
##   is missing in the configuration, a message will be printed out via
##   NOTES.txt.
udpServer:
  port: ""

## Deployment configuration options.
deployment:
  annotations: {}
  labels: {}
  replicas: 1

## Pod configuration options.
pod:
  annotations: {}
  labels: {}
  securityContext: {}
    # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## Service configurations for the emulator plugin.
## ref: http://kubernetes.io/docs/user-guide/services/
##
## The port here should match the network address in the
## plugin configuration, below.
service:
  port: 5010
  annotations: {}
  labels: {}

## Readiness and liveness probe configuration options
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  timeoutSeconds: 2
  periodSeconds: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 5

## Pass arguments to the plugin container. For additional startup
## logging, you can pass the --debug flag. By default, no additional
## arguments are passed to the container.
#args: ["--debug"]
args: []

## Allow pass-through environment variable configuration.
env: []

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Synse Plugin configuration.
## The plugin requires a plugin configuration to be provided. This should be
## specified on a per-release level. It is left empty here.
#config:
#  version: 3
#  debug: true
#  network:
#    type: tcp
#    address: ":5010"
config: {}
