apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    synse-component: plugin
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | trim | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
    - port: {{ .Values.udpServer.port }}
      targetPort: udpServer
      name: udpServer
      protocol: UDP
    {{- if .Values.metrics.enabled }}
    - port: 2112
      targetPort: metrics
      name: metrics
    {{- end }}
  selector:
    synse-component: plugin
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
