apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    synse-component: plugin
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
      nodePort: null
    - port: {{ .Values.service.jti.port }}
      targetPort: jti
      name: jti
      protocol: UDP
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.jti.nodePort))) }}
      nodePort: {{ .Values.service.jti.nodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: 2112
      targetPort: metrics
      name: metrics
      nodePort: null
    {{- end }}
  selector:
    synse-component: plugin
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
