apiVersion: v1
kind: Service
metadata:
  name: {{ include "juniper-jti.fullname" . }}-synse
  {{- with .Values.service.synse.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    vapor.io/synse: plugin
    {{- include "juniper-jti.labels" . | nindent 4 }}
    {{- with .Values.service.synse.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.synse.type | default "ClusterIP" }}
  {{- if (or (eq .Values.service.synse.type "ClusterIP") (empty .Values.service.synse.type)) }}
  clusterIP: {{ .Values.service.synse.clusterIP | default "" }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.synse.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "juniper-jti.selectorLabels" . | trim | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "juniper-jti.fullname" . }}-jti
  {{- with .Values.service.jti.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    {{- include "juniper-jti.labels" . | nindent 4 }}
    {{- with .Values.service.jti.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.jti.type | default "ClusterIP" }}
  {{- if (or (eq .Values.service.jti.type "ClusterIP") (empty .Values.service.jti.type)) }}
  clusterIP: {{ .Values.service.jti.clusterIP | default "" }}
  {{- end }}
  ports:
    - name: jti
      port: {{ .Values.service.jti.port }}
      targetPort: jti
      protocol: UDP
      {{- if (and (eq .Values.service.jti.type "NodePort") (not (empty .Values.service.jti.nodePort))) }}
      nodePort: {{ .Values.service.jti.nodePort }}
      {{- end }}
  selector:
    {{- include "juniper-jti.selectorLabels" . | trim | nindent 4 }}

{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "juniper-jti.fullname" . }}-metrics
  labels:
    {{- include "juniper-jti.labels" . | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "juniper-jti.selectorLabels" . | trim | nindent 4 }}
{{- end }}
