apiVersion: v2
type: application
name: snmp
version: 3.1.8
appVersion: 2.2.2 # Same as image tag.
description: SNMP plugin for Synse
home: https://github.com/vapor-ware/synse-snmp-plugin
icon: https://charts.vapor.io/.images/synse-snmp.jpg
sources:
  - https://github.com/vapor-ware/synse-snmp-plugin.git
maintainers:
- name: Matthew Hink
  email: mhink@vapor.io
- name: Marco Ceppi
  email: marco@vapor.io
