# Default values for the SNMP plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/snmp-plugin
  tag: edge

service:
  port: 5003

resources:
  requests:
   cpu: 33m
   memory: 150Mi

parameters:
  pressure:
    high: 50
    low: -100
    proportionalControl: .6
    integralControl: .1
    differentialControl: 0

vecs:
  # Currently using Austin vec config as the default.
  - name: w1    # Name is convenience only. All calls to remote vecs are made by IP.
    ip: 10.193.1.1   # Used to call to remote vecs. Internal VEC IP.
    role: leader     # Roles are currently unused (6/19/17)
  - name: w2
    ip: 10.193.1.2
    role: follower
  - name: w3
    ip: 10.193.1.3
    role: follower
  - name: w4
    ip: 10.193.1.4
    role: follower
  - name: w5
    ip: 10.193.1.5
    role: follower
  - name: w6
    ip: 10.193.1.6
    role: follower

nodeSelector: {}

tolerations: []

affinity: {}

# Component 
component: plugin
