# Default values for the SNMP plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/snmp-plugin
  tag: edge

service:
  type: "clusterIP: None"
  port: 5003

resources:
  requests:
   cpu: 33m
   memory: 150Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Component 
component: plugin
