apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups: [""]                 # Empty string means Core API group
  resources: ["endpoints"]        # Synse Server plugin discovery operates on Endpoint resources
  verbs: ["get", "watch", "list"]
