{{- /*
  Synse Server only needs a ClusterRole definition if plugin discovery
  via the Kubernetes API is configured.
*/ -}}

{{- if .Values.clusterRoles.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups: [""]                 # Empty string means Core API group
  resources: ["endpoints"]        # Synse Server plugin discovery operates on Endpoint resources
  verbs: ["get", "watch", "list"]
{{- end }}