apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
data:
  {{- if .Values.config }}
  config.yml: {{ toYaml .Values.config | quote }}
  {{- end }}