apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selector" . | nindent 6 }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        {{- include "labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "annotations" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      {{- if .Values.config.plugin.discover.kubernetes }}
      # Synse Server is configured to run with plugin discovery using the Kubernetes
      # API. Use the ServiceAccount to give it the proper cluster permissions.
      serviceAccountName: {{ template "fullname" . }}
      {{- end }}
      {{- if .Values.config }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-config
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          hostPort: {{ .Values.service.port }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        {{- /* Allow tuning through env in values.yaml */}}
        {{- if .Values.env }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          initialDelaySeconds: {{ .initialDelaySeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          periodSeconds: {{ .periodSeconds }}
          httpGet:
            path: /test
            port: http
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          initialDelaySeconds: {{ .initialDelaySeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          periodSeconds: {{ .periodSeconds }}
          httpGet:
            path: /test
            port: http
        {{- end }}
        {{- end }}
        {{- if .Values.config }}
        volumeMounts:
        - name: config
          mountPath: /synse/config
        {{- end }}
        {{ if .Values.resources -}}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}