apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "selector" . | indent 6 }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "labels" . | indent 8 }}
      annotations:
{{ include "annotations" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      volumes:
      - name: config
        configMap:
          name: {{ template "name" . }}-config
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          hostPort: {{ .Values.service.port }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        # Basic readiness/liveness probes. These could be expanded upon in the future.
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          httpGet:
            path: /synse/test
            port: http
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /synse/test
            port: http
        volumeMounts:
        - name: config
          mountPath: /synse/config
        {{ if .Values.resources -}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}