apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "selector" . | indent 6 }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "labels" . | indent 8 }}
      annotations:
{{ include "annotations" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      {{- if .Values.config.plugin.discover.kubernetes }}
      # If Synse Server is configured to run with plugin discovery via the
      # Kubernetes API, use the ServiceAccount that was created for it. The
      # ServiceAccount will give Synse Server the proper cluster permissions
      # to use the required Kubernetes API components.
      serviceAccountName: {{ template "fullname" . }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-config
      {{- if and (not (contains "-slim" .Values.image.tag)) (.Values.devices) }}
      - name: emulator-devices
        configMap:
          name: {{ template "fullname" . }}-emulator-devices
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          hostPort: {{ .Values.service.port }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        # Allow tuning through env in values.yaml
        {{- if .Values.env }}
        env:
{{ toYaml .Values.env | indent 10 -}}
        {{- end -}}
        # Basic readiness/liveness probes. These could be expanded upon in the future.
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          httpGet:
            path: /synse/test
            port: http
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /synse/test
            port: http
        {{- if and (not (contains "-slim" .Values.image.tag)) (.Values.devices) }}
        env:
        - name: PLUGIN_DEVICE_CONFIG
          value: /synse/emulator/tmp
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /synse/config
        {{- if and (not (contains "-slim" .Values.image.tag)) (.Values.devices) }}
        - name: emulator-devices
          mountPath: /synse/emulator/tmp
        {{- end }}
        {{ if .Values.resources -}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
