{{- if .Values.ingress.enabled }}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | trim | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ template "fullname" . }}-tls
      hosts:
      {{ toYaml .Values.ingress.tls -}}
  {{- end -}}
  {{- if .Values.ingress.hostname }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.port }}
  {{- else }}
  backend:
    serviceName: {{ template "fullname" . }}
    servicePort: {{ .Values.service.port }}
  {{- end }}
{{- end }}