{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
{{ if .Values.ingress.annotations -}}
{{ toYaml .Values.ingress.annotations | indent 4 -}}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ template "fullname" . }}-tls
      hosts:
      {{ toYaml .Values.ingress.tls -}}
  {{- end -}}
  {{- if .Values.ingress.hostname }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.port }}
  {{- else }}
  backend:
    serviceName: {{ template "fullname" . }}
    servicePort: {{ .Values.service.port }}
  {{- end }}
{{- end }}
