{{- /*
  If Synse Server is configured to run with plugin discovery via the
  Kubernetes API, this template will be rendered. If the Kubernetes
  discovery config is not set, Synse Server will not use the Kubernetes
  API and will not need to be granted additional cluster permissions.
*/ -}}

{{- if .Values.config.plugin.discover.kubernetes }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
{{- end }}