{{- if and .Values.metrics.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.monitoring.serviceMonitor.name | default "synse-server-monitor" }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{ toYaml .Values.monitoring.serviceMonitor.labels | trim | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.monitoring.serviceMonitor.interval | default "60s" }}
    {{- if .Values.monitoring.serviceMonitor.path }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    {{- end }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.timeout | default "30s" }}
    targetPort: {{ .Values.monitoring.serviceMonitor.port }}
  jobLabel: {{ .Values.monitoring.serviceMonitor.name | default "synse-server-monitor" }}
  namespaceSelector:
    matchNames:
    - {{ .Values.monitoring.serviceMonitor.selectorNamespace | default .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      {{-  if .Values.monitoring.serviceMonitor.selectorLabels }}
      {{ toYaml .Values.monitoring.serviceMonitor.selectorLabels }}
      {{- end }}
{{- end }}
