{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synse-loadgen.fullname" . }}-config
  labels:
    {{- include "synse-loadgen.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  config.yaml: {{ toYaml .Values.config | quote }}
{{- end }}