# Default values for the Emulator plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/emulator-plugin
  tag: "2.4.5"
  pullPolicy: Always

## Service configurations for the emulator plugin.
## ref: http://kubernetes.io/docs/user-guide/services/
##
## The port here should match the network address in the
## plugin configuration, below.
service:
  type: "clusterIP: None"
  port: 5001

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
   cpu: 33m
   memory: 150Mi

## Pass arguments to the plugin container. For additional startup
## logging, you can pass the --debug flag. By default, no additional
## arguments are passed to the container.
#args: ["--debug"]
args: []

## Component type
component: plugin

## Synse Emulator Plugin configuration.
config:
  version: 1.1
  debug: true
  network:
    type: tcp
    address: "0.0.0.0:5001"

## Synse Emulator device configurations. If no device configurations
## are specified here, the emulator will use the default built-in
## configurations.
#devices: {}
