# Default values for synse-emulator-plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Partially override the fullname template (will maintain the release name).
nameOverride: ""

## Fully override the fullname template.
fullnameOverride: ""

## Image configuration options.
image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/emulator-plugin
  tag: "3.0.2"
  pullPolicy: Always

## Enable/disable application metrics export via Prometheus.
metrics:
  enabled: false

  ## Labels applied to the metrics service definition. This should be
  ## set when running with Prometheus monitoring so the service monitor
  ## can differentiate the metrics service from other defined services.
  labels: {}

## Prometheus monitoring
monitoring:
  serviceMonitor:
    enabled: false
    name: emulator-monitor
    port: metrics
    path: "/metrics"
    timeout: 4s
    interval: 5s

    # Deploy the ServiceMonitor to a namespace other than the target for the Release. Required in some setups.
    namespace: ""
    # Which namespace the prometheus tooling should interrogate to find services and pods.
    selectorNamespace: ""
    # Labels used to select the services/pods to monitor.
    selectorLabels: {}
    # Labels applied to the ServiceMonitor.
    labels: {}
      #vapor.io/monitor: application

## Deployment configuration options.
deployment:
  annotations: {}
  labels: {}
  replicas: 1

## Pod configuration options.
pod:
  annotations: {}
  labels: {}

## Service configurations for the emulator plugin.
## ref: http://kubernetes.io/docs/user-guide/services/
##
## The port here should match the network address in the
## plugin configuration, below.
service:
  annotations: {}
  labels: {}
  port: 5001

## Readiness and liveness probe configuration options
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 5

## Pass arguments to the plugin container. For additional startup
## logging, you can pass the --debug flag. By default, no additional
## arguments are passed to the container.
#args: ["--debug"]
args: []

## Allow pass-through environment variable configuration.
env: {}

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests: {}
  limits: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Synse Emulator Plugin configuration.
## The emulator plugin image comes pre-built with a default sane configuration.
## The block below may be uncommented if a custom configuration is desired.
#config:
#  version: 3
#  debug: true
#  network:
#    type: tcp
#    address: ":5001"
config: {}

## Synse Emulator device configurations. If no device configurations
## are specified here, the emulator will use the default built-in
## configurations.
devices: {}
