{{- if .Values.config }}
# Plugin configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openconfig.fullname" . }}-config
  labels:
    {{- include "openconfig.labels" . | nindent 4 }}
data:
  config.yml: {{ toYaml .Values.config | quote }}
{{- end }}
