{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openconfig.fullname" . }}-tls-secrets
  labels:
    {{- include "openconfig.labels" . | trim | nindent 4 }}
data:
  {{- with .Values.tls.key }}
  openconfig_key.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.cert }}
  openconfig_cert.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.ca }}
  openconfig_ca.pem: {{ . | b64enc }}
  {{- end }}
{{- end }}

{{- $labs := include "openconfig.labels" . }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    {{- $labs | trim | nindent 4 }}
data:
  secret: {{ $secret.value | b64enc }}

{{- end }}
