{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-tls-secrets
  labels:
    synse-component: plugin
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.tls.key }}
  openconfig_key.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.cert }}
  openconfig_cert.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.ca }}
  openconfig_ca.pem: {{ . | b64enc }}
  {{- end }}
{{- end }}
