{{- if .Values.secrets.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openconfig.fullname" . }}-tls-secrets
  labels:
    {{- include "openconfig.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  {{- with .Values.secrets.tls.key }}
  openconfig_key.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secrets.tls.cert }}
  openconfig_cert.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.secrets.tls.ca }}
  openconfig_ca.pem: {{ . | b64enc }}
  {{- end }}
{{- end }}

{{- /*
  The block below is used to render passwords as secrets. This is needed so we
  can define OpenConfig auth information in a secure way.
*/ -}}
{{- $labs := include "openconfig.labels" . }}
{{- $fullname := include "openconfig.fullname" . }}
{{- range $secret := .Values.secrets.passwords }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-{{ $secret.name | replace "_" "-" }}
  labels:
    {{- $labs | trim | nindent 4 }}
    {{- with $.Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  secret: {{ $secret.value | b64enc }}
{{- end }}
