{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openconfig.serviceAccountName" . }}
  labels:
    {{- include "openconfig.labels" . | trim | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
{{- end }}
