apiVersion: v1
kind: Service
metadata:
  name: {{ include "openconfig.fullname" . }}
  labels:
    {{- include "openconfig.labels" . | trim | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openconfig.selectorLabels" . | nindent 4 }}

{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openconfig.fullname" . }}-metrics
  labels:
    {{- include "openconfig.labels" . | trim | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - port: 2112
      targetPort: metrics
      name: metrics
  selector:
    {{- include "openconfig.selectorLabels" . | nindent 4 }}
{{- end }}
