apiVersion: v1
kind: Service
metadata:
  name: {{ include "openconfig.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    vapor.io/synse: plugin
    {{- include "openconfig.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "openconfig.selectorLabels" . | nindent 4 }}

{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openconfig.fullname" . }}-metrics
  labels:
    {{- include "openconfig.labels" . | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "openconfig.selectorLabels" . | nindent 4 }}
{{- end }}
