{{- if .Values.config }}
# Plugin configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snmp.fullname" . }}-config
  labels:
    {{- include "snmp.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  config.yml: {{ toYaml .Values.config | quote }}
{{- end }}

{{- if .Values.devices }}
---
# Device configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snmp.fullname" . }}-devices
  labels:
    {{- include "snmp.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  config.yml: {{ toYaml .Values.devices | quote }}
{{- end }}
