name: publish-charts
description: "Publishes a helm chart to GCS bucket"
inputs:
  bucket_name:
    type: string
    description: "Name of GCS bucket (charts.vio.sh for private and charts.vapor.io for public)"
    default: false
    required: true
secrets:
  VIO_BUILD_SA:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.VIO_BUILD_SA }}
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
    - name: Package
      run: |
        helm package --dependency-update --destination .chart-staging charts/*
    - name: Index
      env:
        NAME: ${{ inputs.bucket_name }}
      run: |
        curl https://$NAME/index.yaml > index.yaml
        helm repo index --url https://$NAME --merge ./index.yaml .chart-staging/
      shell: bash
    - name: Sync
      env:
        NAME: ${{ inputs.bucket_name }}
      run: |
        gsutil -m rsync .chart-staging gs://$NAME
        gsutil setmeta -h Cache-Control:no-cache,max-age=0 -h Content-Type:text/yaml -h Content-Encoding:UTF-8 gs://$NAME/*.yaml
      shell: bash
