apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "selector" . | indent 6 }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "labels" . | indent 8 }}
      annotations:
{{ include "annotations" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      volumes:
      - name: plugin-config
        configMap:
          name: {{ template "name" . }}-plugin
      - name: device-config
        configMap:
          name: {{ template "name" . }}-devices
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        volumeMounts:
        - name: plugin-config
          mountPath: /etc/synse/plugin/config
        - name: device-config
          mountPath: /etc/synse/plugin/config/device
        {{ if .Values.resources -}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}