# Default values for synse-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Deployment replication configuration.
replicaCount: 1

## Override the serialized names which are typically $release-name-$app
fullNameOverride: ""

## Enable/disable the creation of a ClusterRole, ClusterRoleBinding, and
## ServiceAccount. This is false by default, as Synse does not need additional
## permissions with its default settings.
##
## If Synse Server is configured for plugin discovery via the Kubernetes API,
## this must be enabled.
clusterRoles:
  enabled: false

## Image configuration options.
image:
  registry: "" # Add a registry if we need to use the non-default one
  repository: vaporio/synse-server
  tag: "v3.0.0-alpha.2"
  pullPolicy: Always

## Service configuration options.
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP
  port: 5000

## Ingress configuration options.
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: ""
  tls: []

## Allow pass-through environment variable configuration.
#env: {}

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
   cpu: 33m
   memory: 150Mi

## Specify arguments to pass to the container. By default, no arguments are passed.
args: []

## Readiness and liveness probe configuration options
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 5


## Synse Server configuration. This configuration is placed into a ConfigMap where
## it is then mounted into the container. The config options here can be overridden
## with environment variables, if desired. For more information on configuring Synse
## Server, see: https://synse.readthedocs.io/en/latest/server/user/configuration/
# config: {}