{{- if .Values.ingress.enabled -}}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "prophetess.fullname" . }}
  labels:
    app: {{ template "prophetess.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{ if .Values.ingress.annotations -}}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 -}}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "prophetess.fullname" . }}
              servicePort: {{ default 80 .Values.service.port }}
{{ if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.domain }}-tls
{{- end }}
{{- end }}
