apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prophetess.fullname" . }}
  labels:
    {{- include "prophetess.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
type: Opaque
data:
  pipeline.yaml: {{ toYaml .Values.config | b64enc }}
