apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prophetess.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "prophetess.fullname" . }}
type: Opaque
data:
  pipeline.yaml: {{ toYaml .Values.prophetess.config | b64enc }}
