apiVersion: v1
kind: Service
metadata:
  name: {{ include "prophetess.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prophetess.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "prophetess.selectorLabels" . | trim | nindent 4 }}
