{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prophetess.serviceAccountName" . }}
  labels:
    {{- include "prophetess.labels" . | trim | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
{{- end }}
