apiVersion: v1
kind: Service
metadata:
  name: {{ template "prophetess.fullname" . }}
  labels:
    app: {{ template "prophetess.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
    - port: {{ default 80 .Values.service.port }}
      name: http
      targetPort: {{ default 8080 .Values.prophetess.port }}
  selector:
    app: {{ template "prophetess.fullname" . }}
    release: "{{ .Release.Name }}"
