apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "selector" . | indent 6 }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "labels" . | indent 8 }}
      annotations:
{{ include "annotations" . | indent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      volumes:
      - name: config
        configMap:
          name: {{ template "name" . }}-config
      {{- if .Values.devices }}
      - name: device-config
        configMap:
          name: {{ template "name" . }}-devices
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        env:
        # We need to manually specify a non-default path here. If we
        # mount the config to the default path, the built-in emulator
        # configs will not get picked up.
        - name: PLUGIN_CONFIG
          value: /tmp/synse/plugin
        {{- if .Values.devices}}
        - name: PLUGIN_DEVICE_CONFIG
          value: /tmp/synse/devices
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /tmp/synse/plugin
        {{- if .Values.devices }}
        - name: device-config
          mountPath: /tmp/synse/devices
        {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10}}
        {{- end -}}