---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: {{ template "etamay.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "etamay.fullname" . }}
data:
  api.yaml: |
{{ toYaml .Values.config | indent 4 }}
