{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "etamay.fullname" . }}
  labels:
    app: {{ template "etamay.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  annotations:
{{ if .Values.ingress.annotations -}}
{{ toYaml .Values.ingress.annotations | indent 4 -}}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "etamay.fullname" . }}
              servicePort: 80
{{ if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.domain }}-tls
{{- end }}
{{- end }}
