{{- if .Values.config }}
# Plugin configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snmp-ups.fullname" . }}-config
  labels:
    {{- include "snmp-ups.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
data:
  config.yml: {{ toYaml .Values.config | quote }}
{{- end }}
