apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emulator.fullname" . }}
  labels:
    {{- include "emulator.labels" . | trim | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "emulator.selectorLabels" . | trim | nindent 6 }}
  template:
    metadata:
      name: {{ include "emulator.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.pod.annotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      labels:
        {{- include "emulator.selectorLabels" . | trim | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 3
      serviceAccountName: {{ include "emulator.serviceAccountName" . }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- if (or .Values.config .Values.devices) }}
      volumes:
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ include "emulator.fullname" . }}-config
        {{- end }}
        {{- if .Values.devices }}
        - name: devices
          configMap:
            name: {{ include "emulator.fullname" . }}-devices
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 2112
              protocol: TCP
            {{- end }}
          {{- with .Values.args }}
          args: {{ . }}
          {{- end }}
          env:
            - name: PLUGIN_METRICS_ENABLED
              value: {{ .Values.metrics.enabled | quote }}
            {{- with .Values.env }}
            {{- toYaml . | trim | nindent 12 }}
            {{- end }}
          {{- if (or .Values.config .Values.devices) }}
          volumeMounts:
            {{- if .Values.config }}
            - name: config
              mountPath: /etc/synse/plugin/config/config.yml
              subPath: config.yml
            {{- end }}
            {{- if .Values.devices }}
            - name: devices
              mountPath: /etc/synse/plugin/config/device
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            exec:
              command:
                - /bin/exists
                - /etc/synse/plugin/healthy
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
            exec:
              command:
                - /bin/exists
                - /etc/synse/plugin/healthy
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | trim | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
