{{- /*
  Synse Server only needs a ClusterRole definition if plugin discovery
  via the Kubernetes API is configured.
*/ -}}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "synse-server.fullname" . }}
  labels:
    {{- include "synse-server.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "synse-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "synse-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}