{{- /*
  Synse Server only needs a ClusterRole definition if plugin discovery
  via the Kubernetes API is configured.
*/ -}}
{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synse-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synse-server.labels" . | trim | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
{{- end }}
