name: charts
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-charts:
    name: 'Validate'
    uses: ./.github/workflows/validate-charts.yml
    with:
      k8s_version: 1.24.15
      charts_path: 'charts/*'

  publish:
    name: 'Publish'
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [validate-charts]
    uses: ./.github/workflows/publish-charts.yml
    with:
      bucket_name: charts.vapor.io
